# -*- coding: utf-8 -*-
# vim: ft=yaml
---
include:
  - project: EOLE/infra/ci-tools
    ref: stable
    file: /templates/Rules.yaml
  - project: EOLE/infra/ci-tools
    ref: stable
    file: /templates/Runners/apps.education-docker.yaml

variables:
  # `ci-tools` default branch is `stable`
  STABLE_BRANCH: master

stages:
  - deps
  - lint
  - test

# Common setup for all meteor based jobs
.meteor:
  extends: .not-on-stable
  image: hub.eole.education/proxyhub/geoffreybooth/meteor-base:2.5
  cache:
    key:
      files:
        # Generate new cache when one of the file changes
        - package.json
        - package-lock.json
    paths:
      - node_modules/
    # Only use the cache created by `cache-dependencies` job
    policy: pull
  variables:
    METEOR_ALLOW_SUPERUSER: "true"


###############################################################################
# `deps` stage: to download and cache dependencies
###############################################################################
cache-dependencies:
  stage: deps
  extends: .meteor
  cache:
    # This job update dependencies
    policy: pull-push
  script:
    - meteor npm ci


###############################################################################
# `lint` stage: `meteor-lint`
###############################################################################
meteor-lint:
  stage: lint
  extends: .meteor
  script:
    - meteor npm install --only=dev
    - meteor npm run lint


###############################################################################
# `test` stage: `meteor-tests`
###############################################################################
meteor-tests:
  stage: test
  extends: .meteor
  script:
    - meteor npm test
